import { Link } from '@tanstack/react-router'
import { ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, GitBranch, ShieldCheck, Sparkles } from 'lucide-react'
import { Badge } from '../components/ui/badge'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { useI18n } from '../contexts/i18n-context'

const signalData = [{ key: 'tests', value: 96, icon: ShieldCheck, color: 'text-emerald-500', bar: 'bg-emerald-500' }, { key: 'incidents', value: 88, icon: CircleAlert, color: 'text-amber-500', bar: 'bg-amber-500' }, { key: 'observability', value: 91, icon: Sparkles, color: 'text-brand-500', bar: 'bg-brand-500' }, { key: 'rollback', value: 100, icon: GitBranch, color: 'text-violet-500', bar: 'bg-violet-500' }, { key: 'ownership', value: 100, icon: CheckCircle2, color: 'text-cyan-500', bar: 'bg-cyan-500' }]
export function Dashboard() { const { t } = useI18n(); const confidence = 94
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold text-brand-600">{t('overview')}</p><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{t('production')}</h1><p className="mt-2 max-w-xl text-slate-500 dark:text-slate-400">{t('subtitle')}</p></div><Button><Sparkles size={16} />{t('configure')}</Button></div><Card className="overflow-hidden border-0 bg-gradient-to-br from-brand-700 to-brand-500 text-white"><CardContent className="flex flex-col justify-between gap-8 p-7 sm:flex-row sm:items-center"><div><Badge className="bg-white/15 text-white">{t('healthy')}</Badge><p className="mt-5 text-sm text-blue-100">{t('confidence')}</p><div className="mt-1 flex items-end gap-3"><span className="text-6xl font-extrabold tracking-tighter">{confidence}</span><span className="mb-2 text-2xl font-bold">/100</span></div><p className="mt-2 text-sm text-blue-100">{t('lastUpdated')}</p></div><div className="relative flex h-36 w-36 items-center justify-center rounded-full border-[12px] border-white/20 sm:me-10"><div className="absolute inset-0 rounded-full border-[12px] border-transparent border-t-white border-r-white rotate-[25deg]" /><span className="text-2xl font-bold">A+</span></div></CardContent></Card><div><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-bold">{t('signals')}</h2><p className="text-sm text-slate-500">Five independent checks are contributing to this score.</p></div><Link to="/details" className="flex items-center gap-1 text-sm font-bold text-brand-600">{t('details')}<ArrowUpRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{signalData.map(({ key, value, icon: Icon, color, bar }) => <Card key={key}><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><span className={cnIcon(color)}><Icon size={18} /></span><span className="text-lg font-extrabold">{value}<small className="text-xs font-medium text-slate-400">/100</small></span></div><p className="font-bold">{t(key as 'tests' | 'incidents' | 'observability' | 'rollback' | 'ownership')}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${bar}`} style={{ width: `${value}%` }} /></div></CardContent></Card>)}</div></div><Card><CardHeader><CardTitle>{t('actions')}</CardTitle><CardDescription>Small improvements that make the release even safer.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Action text="Add one more checkout flow to the smoke suite" /><Action text="Schedule a post-release metric review" /></CardContent></Card></div> }
function cnIcon(color: string) { return `inline-flex rounded-lg bg-slate-100 p-2 ${color} dark:bg-slate-800` }
function Action({ text }: { text: string }) { return <div className="flex items-center justify-between rounded-xl border p-4 dark:border-slate-800"><div className="flex items-center gap-3 text-sm font-medium"><span className="h-2 w-2 rounded-full bg-amber-400" />{text}</div><ChevronRight className="text-slate-400" size={17} /></div> }
