import { useState, type FormEvent } from 'react'
import { z } from 'zod'
import { Check, Save } from 'lucide-react'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { Input } from '../components/ui/input'
import { Select } from '../components/ui/select'
import { useI18n } from '../contexts/i18n-context'

const profileSchema = z.object({ name: z.string().trim().min(2, 'Release name must contain at least 2 characters.'), environment: z.enum(['Production', 'Staging', 'Preview']), owner: z.string().trim().min(2, 'Add a release owner.') })
type Profile = z.infer<typeof profileSchema>
export function Settings() { const { t, locale, setLocale } = useI18n(); const [profile, setProfile] = useState<Profile>({ name: 'Checkout 4.8.0', environment: 'Production', owner: 'Maya Chen' }); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
 const update = (field: keyof Profile, value: string) => { setProfile(current => ({ ...current, [field]: value } as Profile)); setSaved(false) }
 const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const result = profileSchema.safeParse(profile); if (!result.success) { setError(result.error.issues[0]?.message ?? 'Check the form.'); setSaved(false); return }; setError(''); setSaved(true) }
 return <div className="max-w-3xl space-y-7"><div><h1 className="text-3xl font-extrabold">{t('settings')}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Personalize the release profile and your workspace.</p></div><Card><CardHeader><CardTitle>{t('configure')}</CardTitle><CardDescription>These values label the readiness report for your team.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><label className="block space-y-2"><span className="text-sm font-semibold">{t('releaseName')}</span><Input value={profile.name} onChange={event => update('name', event.target.value)} /></label><label className="block space-y-2"><span className="text-sm font-semibold">{t('environment')}</span><Select value={profile.environment} onChange={event => update('environment', event.target.value)}><option>Production</option><option>Staging</option><option>Preview</option></Select></label><label className="block space-y-2"><span className="text-sm font-semibold">{t('owner')}</span><Input value={profile.owner} onChange={event => update('owner', event.target.value)} /></label>{error && <p className="text-sm font-semibold text-rose-600">{error}</p>}<Button type="submit"><Save size={16} />{t('save')}</Button>{saved && <span className="ms-3 inline-flex items-center gap-1 text-sm font-semibold text-emerald-600"><Check size={16} />Saved successfully</span>}</form></CardContent></Card><Card><CardHeader><CardTitle>{t('language')} &amp; {t('theme')}</CardTitle><CardDescription>Choose how Release Radar feels and reads.</CardDescription></CardHeader><CardContent><div className="grid gap-5 sm:grid-cols-2"><label className="space-y-2"><span className="text-sm font-semibold">{t('language')}</span><Select value={locale} onChange={event => setLocale(event.target.value as 'en' | 'ar')}><option value="en">{t('english')}</option><option value="ar">{t('arabic')}</option></Select></label><div className="space-y-2"><span className="block text-sm font-semibold">{t('theme')}</span><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500 dark:bg-slate-800">Use the sun/moon control in the top bar to switch appearance.</p></div></div></CardContent></Card></div> }
