import { Link } from '@tanstack/react-router'
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, GitBranch, ShieldCheck, Sparkles } from 'lucide-react'
import { Badge } from '../components/ui/badge'
import { Card, CardContent } from '../components/ui/card'
import { useI18n } from '../contexts/i18n-context'

const rows = [{ key: 'tests', score: 96, icon: ShieldCheck, status: 'success', detail: '428 of 446 critical-path assertions passed in the latest pipeline.' }, { key: 'incidents', score: 88, icon: CircleAlert, status: 'warning', detail: 'One low-severity incident remains under observation from the last 7 days.' }, { key: 'observability', score: 91, icon: Sparkles, status: 'success', detail: 'All key service-level indicators have alert thresholds and owners.' }, { key: 'rollback', score: 100, icon: GitBranch, status: 'success', detail: 'Rollback package was verified in staging 2 hours ago.' }, { key: 'ownership', score: 100, icon: CheckCircle2, status: 'success', detail: 'Release and on-call owners have both acknowledged the window.' }]
export function SignalDetails() { const { t, locale } = useI18n(); const Back = locale === 'ar' ? ArrowRight : ArrowLeft
 return <div className="space-y-7"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-brand-600"><Back size={16} />{t('back')}</Link><div><h1 className="text-3xl font-extrabold">{t('signals')}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">{t('detailsIntro')}</p></div><div className="space-y-4">{rows.map(({ key, score, icon: Icon, status, detail }) => <Card key={key}><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4 sm:w-56"><span className="rounded-xl bg-brand-50 p-3 text-brand-600 dark:bg-brand-950"><Icon size={20} /></span><span className="font-bold">{t(key as 'tests' | 'incidents' | 'observability' | 'rollback' | 'ownership')}</span></div><div className="flex-1"><div className="mb-2 flex justify-between text-sm"><span className="text-slate-500">{detail}</span><strong>{score}/100</strong></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${status === 'warning' ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${score}%` }} /></div></div><Badge variant={status === 'warning' ? 'warning' : 'success'}>{status === 'warning' ? t('improve') : t('allClear')}</Badge></CardContent></Card>)}</div></div> }
